INSERT INTO rpggremlins.ability(
    index,
    name
)
Values(
          'str',
          'Strength'
      ),(
          'dex',
          'Dexterity'
      ),(
          'con',
          'Constitution'
      ),(
          'int',
          'Intelligence'
      ),(
          'wis',
          'Wisdom'
      ),(
          'cha',
          'Charisma'
      )