INSERT INTO rpggremlins.skill(ability_id,
                              name)
VALUES (2, 'Acrobatics'),
       (5, 'Animal Handling'),
       (4, 'Arcana'),
       (1, 'Athletics'),
       (6, 'Deception'),
       (4, 'History'),
       (5, 'Insight'),
       (6, 'Intimidation'),
       (4, 'Investigation'),
       (5, 'Medicine'),
       (4, 'Nature'),
       (5, 'Perception'),
       (6, 'Performance'),
       (6, 'Persuasion'),
       (4, 'Religion'),
       (2, 'Slight of Hand'),
       (2, 'Stealth'),
       (5, 'Survival')